[package]
name = "bitcoin_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitcoin = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.117"
hex = "0.4.3"
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = "0.6.5"
ic-btc-interface = { workspace = true }
thiserror = "1.0.65"

[features]
types = []
canister = []
default=["canister", "types"]