[package]
name = "ramp_backend"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = { workspace = true }
bitcoin = { workspace = true }
bitcoin_backend = { workspace = true }
candid = { workspace = true }
email_address = "0.2.5"
ethers-core = "2.0.14"
evm-rpc-canister-types = "5.0.1"
futures = "0.3"
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4.3"
ic-cdk = "0.14"
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
icrc-ledger-types = "0.1.6"
num-traits = { workspace = true }
pbkdf2 = { version="0.12.2", features = ["simple"] }
ramp_types = { workspace = true }
rand = "0.8"
rsa = "0.6"
serde = { workspace = true }
serde_bytes = "0.11.12"
serde_json = "1.0.117"
secp256k1 = { version = "0.30", features = [ "global-context", "recovery" ] }
sha2 = "0.10"
thiserror = "1.0"
