[package]
name = "ramp_types"
version.workspace = true
edition.workspace = true

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true }
sol_rpc_types  = { workspace = true }
solana-pubkey = { workspace = true }
thiserror = { workspace = true }