[package]
name = "solana"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-ed25519 = { workspace = true }
ic-stable-structures = { workspace = true }
icramp_types = { workspace = true }
base64 = { workspace = true }
bs58 = { workspace = true }
candid = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sol_rpc_client = { package = "sol_rpc_client", git = "https://github.com/dfinity/sol-rpc-canister", rev = "715f278", features = ["ed25519"], default-features = false }
sol_rpc_types  = { workspace = true }
solana-program = "=2.3.0"
solana-signature = "=2.3.0"
solana-transaction = "=2.2.3"
solana-transaction-status-client-types = "=2.3.3"
solana-message = "=2.4.0"
solana-pubkey = { workspace = true }
solana-instruction = "=2.3.0"
solana-system-interface = "1.0.0"
thiserror = { workspace = true }

[dependencies.getrandom]
version = "0.2.16"
default-features = false
features = ["custom"]

[features]
default = []
