[package]
name = "bitcoin_tests"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dev-dependencies]
bitcoincore-rpc = "0.19"
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-btc-interface = { workspace = true }
icramp_types = { workspace = true }
lazy_static = { workspace = true }
pocket-ic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
testkit = { workspace = true }